name: SauceDemo Practice

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: "Pick the browser"
        required: true
        options:
          - "chromium"
          - "firefox"
          - "webkit"


jobs:
  test:
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - name: Branch checkout
        uses: actions/checkout@v4
      
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
        
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Install Playwrights Browsers
        run: python -m playwright install --with-deps

      - name: Run Test Cases
        run: pytest --tracing retain-on-failure

      - name: Upload Playwright Traces
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Run Linting
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          flake8 .
